### ISSUE TITLE
Kubernete Pods are evicted

### ISSUE THREAD

**Issue by onion1984** [sassoftware/sas-container-recipes#12] opened 2019-03-05 01:34 UTC
Hi,

I have followed the instructions to built multi-container visual analytics on CentOS and I deployed it into Azure Kubernetes Service (AKS). The cluster only consist of 1 worker node, with 32 core and 256G RAM.

After the deployment, the administrativeservices pod status shows error after it ran for a while, and the rest of the Pods' status start to show error too. Eventually all Pods were Evicted. 

![screenshot](https://user-images.githubusercontent.com/16892845/53774509-cdc59d80-3f29-11e9-880d-e506e1cf7cc9.JPG)

**Comment by g8sman** [comment] 2019-03-05 12:46
Hi...I have never seen where one pod was replicated so many times. My first guess is that the amount of memory needed for the pods is greater than the one node can handle. I have some questions. 

- Was this the only pod that was deployed? 
- Did you change the replica count?
- Did you try a describe on the pod as it was being evicted to see if there was more information given?

Cheers!

**Comment by onion1984** [comment] 2019-03-05 13:10
To answer your questions
1. This is not the only pod. I deployed all the pods in the visual mpp directory. The rest of the pods all look like this
2. I did not change the replica number, and I also didn't try to scale the pods. Once a pod is being evicted, Kubernetes will start another pod, again and again. That's why you see so many evicted pods in the screenshot
3. I will try to decribe the pod and post the information here later

**Comment by TanJicong** [comment] 2019-03-06 03:50
Hi,
I read the build instruction again, I noticed that the wording "Only Red Hat Enterprise Linux 7 based images are supported for recipes" for multi container build. Does it matter if my containers are built using CentOS as the base image?

**Comment by TanJicong** [comment] 2019-03-07 07:45
Issue closed. The root cause is because AKS is not able to pull all the docker images due to my Docker Hub setting

**Comment by g8sman** [comment] 2019-03-07 13:06
Thanks @TanJicong. Will close the issue. Are you using DockerHub as your registry?

**Closed by g8sman** 2019-03-07 13:06 UTC
Labels: area/full-deployment, status/more-info-needed, type/bug

**Comment by onion1984** [comment] 2019-03-07 22:57
yes, i was using docker hub initially with private repo. I have removed all the docker images after that
